frontend/public/locales/en/translation.json
frontend/public/locales/ko/translation.json
frontend/src/components/users/FollowButton.jsx

팔로우 요청을 취소하려고 할 때, 언팔로우하려고 할 때 확인창을 띄웁니다.

FollowButton: 언팔로우 전에 확인하기

---

frontend/src/assets/themes.js
frontend/src/components/navbar/Navbar.jsx
frontend/src/components/sidebar/Header.jsx
frontend/src/components/sidebar/Middle.jsx
frontend/src/components/sidebar/Sidebar.jsx
frontend/src/components/sidebar/SidebarContext.jsx
frontend/src/components/sidebar/SidebarLink.jsx
frontend/src/containers/Layout.jsx

- 이제 모바일에서 `Sidebar`를 사용하지 않습니다.
- `Sidebar`에서 모바일 대응 코드를 삭제했습니다.
- `Navbar` 디자인과 항목 목록을 개편했습니다.
- 알림과 설정은 어떻게 접근하나요?
`Home`에서 접근할 수 있도록 추가할 예정입니다. (현재 개발중인 홈 스크린샷)

새로운 모바일 Navbar

---

frontend/src/components/project/dragAndDown/DragAndDownBox.jsx
frontend/src/components/tasks/Priority.jsx
frontend/src/components/tasks/TaskFrame.jsx

작업의 이름, 중요도 아이콘, 날짜 아이콘을 드래그하면 작업이 드래그되지 않고 해당 요소만 드래그되는 문제를 해결합니다.
**Before**
https://github.com/user-attachments/assets/1a7858d7-7099-4f5e-94ec-bd4d98b43b81
**After**
https://github.com/user-attachments/assets/dc9716bf-5979-44b6-9c8b-20a0faf44814
- `DragAndDownBox`의 모든 하위 요소에 `user-select: none`을 추가해 드래그 시 글자 선택이 되지 않도록 했습니다.
- `TaskFrame`의 작업 이름, 중요도 아이콘, 할당 날짜/기한/리마인더 아이콘에 `draggable="false"`를 추가해 해당 요소만 드래그되는 일이 없도록 했습니다.
- `Priority` 컴포넌트를 리팩토링했습니다.
- `TaskFrame`의 임포트 경로를 정리했습니다.

Task: 모든 요소가 드래그되도록 수정

---

.env.example
backend/django_peak/settings.py

이제 유저 기본 프로필 이미지를 `.env` 파일에서 수정할 수 있습니다.
본 프로젝트에 기여하시는 분들은 `.env` 파일 맨 아래에 아래 줄을 추가해주세요.
```bash
USER_DEFAULT_PROFILE_IMG=https://alpha-media.peak.ooo/user_profile_imgs/default.jpg
```
(맨 아래 줄 개행을 잊지 마세요!)
그리고, `api` 컨테이너를 재생성 후 실행해야 합니다.
```bash
docker compose create api
docker compose start api
```

USER_DEFAULT_PROFILE_IMG 설정을 .env에 추가

---

frontend/src/components/users/ProjectList.jsx

#267 이슈에 맞게 `UserPage`를 수정했습니다.

Fix UserPage: 모바일에서의 프로젝트 목록 왼쪽 여백 감소 #267

---

backend/api/exceptions.py
backend/api/mixins.py
backend/notifications/views.py
backend/requirements.txt
backend/tasks/views.py

- pytz 라이브러리와 `datetime.combine`을 함께 사용하면 역사적 시간대가 잡히는 문제가 보고되어, `TimezoneMixin`과 본 프로젝트 전체에서 pytz 라이브러리 사용을 중단하고 파이썬 내장 [zoneinfo](https://docs.python.org/3/library/zoneinfo.html#) 라이브러리로 변경했습니다.
- `TimezoneMixin`에서 `AttributeError`가 발생하는 상황이 있어 에러 메시지를 추가했습니다.

TimezoneMixin: pytz를 zoneinfo로 변경

---

frontend/src/components/settings/Select.jsx
frontend/src/pages/settings/Account.jsx

- 전:
- 후:
모바일 화면에서의 여백을 조정하고 유저네임과 이메일이 너무 길면 말줄임표로 짧아지도록 조정했습니다.
- 전:
- 후:

SettingsPage: Select 너비 조정 & Account 여백 조정

---

frontend/src/pages/NotificationsPage.jsx

- 전: `/app/notifications/`에 접속하면 `?active=all`이 추가되면서 히스토리가 하나 추가되었습니다. (뒤로가기하면 여전히 알림 페이지)
- 후: `?active=all`이 추가될 때 `replace`가 되면서 히스토리 개수에 변화가 없습니다. (뒤로 가기하면 정상적으로 이전 페이지로 돌아감)

NotificationsPage: searchParam 추가 시 replace

---

frontend/src/components/navbar/Navbar.jsx

- iOS Safari에서 `Navbar`의 `Item`을 터치하면 항목의 배경이 어둡게 깜빡거리는 현상을 해결합니다.
- `user-select: none`을 추가하여 `Navbar`가 텍스트 선택의 대상이 되지 않도록 수정했습니다.
**Before**
https://github.com/user-attachments/assets/4e2bc45a-372b-4105-950f-07da0e14dd04
**After**
https://github.com/user-attachments/assets/38f9dd9d-06e8-40e2-b970-2c1c0618c11f
- [iPad Safari: How to disable the quick blinking effect when a link has been hit](https://stackoverflow.com/questions/3516173/ipad-safari-how-to-disable-the-quick-blinking-effect-when-a-link-has-been-hit)

Navbar: iOS에서 항목 터치 시 항목이 깜빡거리는 현상 해결

---

frontend/src/components/project/taskDetails/mobile/ContentsMobile.jsx

모바일 `TaskCreate/Detail`의 `AlarmClock`과 `Hourglass`가 `.svg `파일로 입력되어있어 오류가 일어나던 현상을 수정했습니다.

모바일 TaskCreate/Detail의 icon이 제대로 입력되지 않은 문제 해결

---

frontend/src/pages/settings/Account.jsx

**설정** > **계정**에서 표시되는 이메일의 `g`, `p`, `q` 등의 알파벳이 짤려서 표시되던 문제를 해결했습니다.
**Before**
**After**

설정>계정: 이메일이 짤리던 문제 해결

---

.github/workflows/reviewer.yaml

- [random-reviewer-discord](https://github.com/JedBeom/random-reviewer-discord) 액션을 추가했습니다.
- PR을 올릴 때 리뷰어가 지정되어 있으면 봇은 아무 행동을 하지 않습니다. 그러니 리뷰어가 정해진 PR은 PR 업로더가 수동으로 노티를 주는 게 방법일 것 같습니다.

랜덤 리뷰어 지정 액션 추가

---

frontend/eslint.config.js
frontend/src/pages/SocialExplorePage.jsx

현재 `/social/explore` 접속 시 오류가 발생하는 문제가 있습니다. #312 PR에서 `SocialExplorePage` 속 `searchQuery` 변수를 `queryKey`에 추가하면서 변수가 초기화되기 전에 접근하게 되어 발생하는 오류입니다.
- `SocialExplorePage`의 `searchQuery` 초기화 구문을 `useInfinity` 함수보다 위로 이동해서 초기화가 먼저 실행되도록 했습니다.
- `eslint.config.js`에 `no-use-before-define` 규칙이 에러를 발생시키도록 설정했습니다. ([ESLint 문서](https://eslint.org/docs/latest/rules/no-use-before-define#options)) 클래스, 그리고 같은 스코프에 있는 변수만 규칙이 적용되며, 함수와 상위 스코프의 변수에는 변함없이 규칙이 적용되지 않습니다.

eslint에 no-use-before-define 규칙 추가

---

frontend/public/locales/en/settings.json
frontend/public/locales/ko/settings.json
frontend/src/components/settings/ProfileImg.jsx
frontend/src/components/settings/Section.jsx
frontend/src/components/sign/Input.jsx
frontend/src/components/sign/Showcase.jsx
frontend/src/components/social/SocialPageTitle.jsx
frontend/src/pages/SettingsPage.jsx
frontend/src/pages/settings/Security.jsx

TOTP 보안키의 길이가 길어 오른쪽으로 짤리던 문제가 있었습니다.
보안키 요소를 textarea로 변경하고 자동 줄바꿈(텍스트 내에 줄바꿈 문자가 삽입되지 않음)이 되어서 짤리지 않습니다. 또한 누르면 바로 전체선택이 되도록 수정했습니다.
모바일 기기에서 도움이 되리라고 생각합니다.
- 현재 작동하지 않는 설정 메뉴인 '공개 범위'와 '리액션'을 숨겼습니다. 라우터에서 제거한 것은 아니라서 주소로는 접근할 수 있습니다.
- 설정 메뉴가 드래그되지 않도록 수정했습니다.
- 설정 섹션 이름과 설명이 드래그되지 않도록 수정했습니다.
- 설정과 로그인/회원가입에서 사용하는 공용 `Input`의 아이콘 윗 여백을 텍스트와 일치하도록 수정했습니다.

TOTP 보안키를 textarea로 변경 외

---

frontend/src/components/common/ModalBottomSheet.jsx
frontend/src/components/drawers/Drawer.jsx
frontend/src/components/project/sorts/SortMenuMobile.jsx
frontend/src/components/project/sorts/SortMenuSelector.jsx
frontend/src/pages/ProjectPage.jsx

모바일용 정렬 뷰를 추가하였습니다.
* 현재 정렬메뉴(모바일, 데스크탑 모두)의 경우, 정렬 기준을 선택할 때마다 새로고침되어 화면이 깜빡깜빡거립니다..

모바일용 정렬 뷰 추가

---

.github/workflows/reviewer.yaml

- random-reviewer-discord 액션의 버전이 지정되어있지 않아서 현 버전인 `v0.1.2`를 명시했습니다.
- 액션 타입을 명확히해서 `synchronize`일 때 실행되지 않도록 설정했습니다.

Specify random-reviewer-discord@v0.1.2

---

.github/workflows/reviewer.yaml

[random-reviewer-discord](https://github.com/JedBeom/random-reviewer-discord) 액션이 v0.2.1로 업데이트 되었다고 합니다.
- 대응하는 이벤트 추가(draft에서 전환되었을 때, 수동으로 리뷰어가 지정되었을 때, 리뷰가 제출되었을 때)
- PR이 닫혔다가 다시 열렸을 때도 지원하지만, 우리는 풀 리퀘스트를 닫았다가 다시 열 일이 없을 것 같아서 제외했습니다.
- 이벤트별 메시지 템플릿 지정 가능
- 리뷰 리마인드 기능 추가: [`schedule.cron`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule)으로 설정 가능하다고 하는데, 깃허브의 cron은 짧으면 30분, 길면 하루 늦게 실행되는 게 예사고 딜레이도 예측이 어렵기 때문에, [`workflow_dispatch`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch)로 외부에 cron을 설정하여 액션을 수동으로 실행...하라고 들었습니다. (깃허브 API로 액션을 수동으로 실행할 수 있습니다)
- 픽 알파서버에 타이머 설정을 해두었습니다. KST 화,금 오후 2시 정각입니다. 
...여기까지가 제가 들은 변경사항입니다. 저번 …

Upgrade random-reviewer-discord to v0.2.1

---

.github/workflows/frontend.yaml
frontend/.prettierrc.js
frontend/README.md
frontend/package.json
frontend/pnpm-lock.yaml
frontend/public/locales/en/settings.json
frontend/public/locales/ko/settings.json
frontend/src/components/common/Switch.jsx
frontend/src/components/home/Header.jsx
frontend/src/components/settings/ImageCropper.jsx
frontend/src/components/settings/PasswordSection.jsx
frontend/src/components/settings/Select.jsx
frontend/src/components/sidebar/Footer.jsx
frontend/src/components/users/UserProfileHeader.jsx
frontend/src/pages/SettingsPage.jsx
frontend/src/pages/settings/Profile.jsx
frontend/src/pages/settings/settings.jsx
frontend/src/routers/settingsChildren.jsx

- '계정'을 '프로필'로 개명했습니다.
| Before | After |
|---|---|
| <img width="182" alt="Screenshot 2025-02-23 at 23 01 03" src="https://github.com/user-attachments/assets/baf0bc19-0941-4056-af12-65c8a085ce89" /> | <img width="182" alt="Screenshot 2025-02-23 at 23 01 11" src="https://github.com/user-attachments/assets/814b5a5f-3242-4c9e-b5aa-c2578191180b" /> |
- '차단'의 아이콘을 '보안'과 겹치는 `shield`에서 `slash`로 변경했습니다. _(보안이 나중에 생긴거지만...)_
| Before | After |
|---|---|
| <img width="109" alt="Screenshot 2025-02-23 at 22 59 06" src="https://github.com/user-attachments/assets/bb228169-4b79-47d6-8a85-ef5caca1502c" /> | <img width="109" alt="Screenshot 2025-02-23 at 22 58 54" src="https://github.com/user-attachments/assets/54d6ee70-9ede-407b-ba80-a370af6b256b" /> |
- `Select`와 `Switch`에 `cursor: pointer` 속성을 추가해 …

설정: '계정'을 '프로필'로 개명 외 & Bump prettier@v3.5.2

---

frontend/src/components/navbar/Navbar.jsx

- Navbar 초기 로딩 시 가장 왼쪽에서 가운데 홈으로 배경이 이동하는 애니메이션이 보이는 문제를 수정했습니다.
- Before:
https://github.com/user-attachments/assets/6eb9fff0-4fec-4fda-8ba4-dce754350dac
- After:
https://github.com/user-attachments/assets/1f1c3f78-4b67-41db-98c6-01faa54e6e53

Navbar의 transition이 처음에는 실행되지 않도록 수정

---

frontend/public/locales/en/translation.json
frontend/public/locales/ko/translation.json
frontend/src/@types/styled.d.ts
frontend/src/assets/palettes.ts
frontend/src/assets/themes.ts
frontend/src/components/home/VGraph.jsx
frontend/src/components/intro/DemoCheer.jsx
frontend/src/components/project/ProjectName.jsx
frontend/src/components/project/common/Progress.jsx
frontend/src/components/project/edit/Color.jsx
frontend/src/components/project/edit/ProjectEdit.jsx
frontend/src/components/project/taskDetails/DrawerFolder.jsx
frontend/src/components/search/SearchResults.jsx
frontend/src/components/sidebar/Middle.jsx
frontend/src/components/social/logDetails/LogDetails.jsx
frontend/src/components/social/logsPreview/LogPreviewBox.jsx
frontend/src/components/today/ImportantTasks.jsx
frontend/src/components/today/TodayAssignmentTasks.jsx
frontend/src/components/users/ProjectList.jsx
frontend/src/components/users/UserProfileHeader.jsx
frontend/src/pages/ProjectPage.jsx
frontend/src/pages/settings/Profile.jsx

- 파일 이동: `frontend/project/common/palette.js` -> `frontend/assets/palette.ts`
- 함수 개명: 색상이 프로젝트 바깥에서도 쓰이므로 `getProjectColor` -> `getPaletteColor`
- 속성 개명: 라이트/다크 테마와의 혼동 방지를 위해 `theme1`를 `palette1`으로 개명
- 타입 추가: `styled-components`에 `LightDark` 타입 추가(`"light"` 혹은 `"dark"`만 허용)
- `Palette` 타입화
- `getPaletteColor`에는 변수값을 넘기는 경우가 많으므로 자동완성이 큰 도움은 되지 않겠지만, 타입스크립트 이주로의 포석으로 이해하시면 됩니다.

Palette 타입화 및 getPaletteColor로의 개명

---

frontend/public/locales/en/home.json
frontend/public/locales/ko/home.json
frontend/src/components/home/AllowNotification.tsx
frontend/src/components/home/InstallPeak.tsx
frontend/src/components/home/Module.tsx
frontend/src/pages/HomePage.tsx

푸시 알림을 켤 것을 추천하는 모듈을 홈에 추가했습니다. 클릭하면 설정>알림 페이지로 이동합니다.
푸시 알림 권한 상태가 `default` 일 때만 홈에 나타납니다. 
- `frontend/components/settings/Module`: 타입화하고 prop 수정이 있었습니다.

홈에 푸시 알림 켜기 모듈 추가

---

frontend/src/utils/pagination.ts

#364 PR에서 함수들의 인자 타입에 `URL`을 포함하는 것을 잊어서... 추가 PR을 올립니다.
- `URL` 생성자가 `URL` 자신도 받기 때문에 `string | URL`인 인자를 그대로 생성자에 전달합니다.
(추가) JS 파일에서 url로 `undefined`를 전달할 가능성도 있기 때문에 조건문을 원복시켰습니다.

pagination 함수 인자 타입에 URL 추가

---

.github/dependabot.yaml
.github/workflows/reviewer.yaml

- 모든 의존성 체크를 '주간'으로 변경했습니다. (UTC 기준 월요일 실행)
- npm과 pip의 마이너 및 패치 버전 업그레이드 PR끼리는 묶도록 설정했습니다. [참고한 글](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates) [공식 문서](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--)
- `django`의 5.0.0 이상 버전은 일단 무시하도록 설정했습니다.
- 액션을 실행한 주체가 dependabot일 경우 `reviewer.yaml`은 실행하지 않도록 설정했습니다.

dependabot PR 그룹화 설정

---

frontend/public/global.css
frontend/src/components/common/Button.tsx
frontend/src/components/settings/ImageCropper.jsx
frontend/src/components/settings/ImageCropper.tsx

#335 PR에서 `ImageCropper`의 버튼 색상을 잘못 옮겼던 것을 고쳤습니다.
| Before | After |
|---|---|
| <img width="345" alt="Screenshot 2025-02-27 at 17 38 23" src="https://github.com/user-attachments/assets/5fb61486-1402-44a0-b9fb-99a00c40003c" /> | <img width="345" alt="Screenshot 2025-02-27 at 17 38 01" src="https://github.com/user-attachments/assets/12393415-1e47-4a20-9780-77c1c6061874" /> |
- `ImageCropper`를 타입스크립트로 옮겼습니다.
- `ButtonGroup`의 prop들을 optional로 바꿨습니다.
- `global.css`에 있던 `ImageCropper` 스타일을 `Cropper`에 객체 형태로 넘기도록 수정했습니다.
- `styled-components`를 사용하지 않는 이유는, `Cropper`에서 `className` prop이 없기 때문입니다.

ImageCropper의 버튼 색상 수정

---

frontend/src/components/home/AllowNotification.tsx

홈의 모듈 중 하나인 `AllowNotification`의 조건문에 `window.Notification`이 `undefined`일 때도 추가했습니다.
iOS Safari에서 앱을 홈 화면에 추가하지 않으면 `window.Notification`이 `undefined`입니다.

window.Notification이 undefined일 때 AllowNotification을 표시하지 않도록 수정

---

backend/django_peak/settings.py
backend/users/auth.py

- 증상: Django Site Admin에서 올바른 유저네임과 암호를 사용해도 로그인할 수 없음
- 원인: #306 PR에서 `backend/django_peak/settings.py`의 `AUTHENTICATION_BACKENDS`에서 `"django.contrib.auth.backends.ModelBackend"`를 제외한 것이 화근 [(diff 보기](https://github.com/GooseMoment/Peak/commit/d532ca74b5897223030f21b3aaa3848f7b35a237#diff-1c6f2a0bcd3ec62fb3939bed9b0a8b839fdf93e419cd2e1ab1f2c3c1e63ebbddR157-L159))
- 해결: `ModelBackend`를 상속하며 요청 경로가 `/admin/`으로 시작하는지 검사하는 `AdminBackend` 추가

Django Admin에 로그인할 수 없던 문제 해결

---

backend/Dockerfile
backend/api/urls.py
backend/django_peak/settings.py
backend/drawers/urls.py
backend/notifications/urls.py
backend/projects/urls.py
backend/tasks/urls.py
backend/tasks/views.py
backend/today/urls.py
frontend/src/api/announcements.api.js
frontend/src/api/drawers.api.js
frontend/src/api/notifications.api.js
frontend/src/api/projects.api.js
frontend/src/api/social.api.js
frontend/src/api/tasks.api.js
frontend/src/api/today.api.js
frontend/src/api/users.api.js

- URL 맨 뒤의 `/`가 있는 엔드포인트와 없는 엔드포인트가 혼재
- 프론트엔드에서 `/`를 빼먹고 요청할 시 리다이렉트가 발생하여 하나의 요청으로 처리할 수 있는 것이 두 번의 요청(리다이렉트 → 원래 응답)이 발생하는 문제
- `backend/*/urls.py`: '모든 URL은 확실해야 한다'는 [장고 철학](https://docs.djangoproject.com/en/4.2/misc/design-philosophies/#definitive-urls)에 맞도록 모든 `urls.py`의 모든 URL 뒤에 슬래시를 추가했습니다.
- `backend/django_peak/settings.py`: [`APPEND_SLASH`](https://docs.djangoproject.com/en/4.2/ref/settings/#append-slash) 값을 거짓으로 설정해서 `/`가 없는 요청이 들어오면 404가 표시되도록 수정했습니다. 
- `backend/Dockerfile`: `health/ok`를 `health/ok/`로 수정했습니다.
- `backend/tasks/views.py`: `ordering`이 `None`인 경우에 대응하는 조건문을 추가했습니다.
- `frontend/src/api/*.api.js`: 모든 URL 뒤에 슬래시를 추가했습니다.

모든 URL 뒷부분에 슬래시 추가

---

frontend/src/components/settings/Select.jsx
frontend/src/components/settings/SettingSwitch.jsx
frontend/src/pages/settings/Appearance.tsx

- `frontend/src/pages/settings/Appearance.tsx`: #393 PR 이후 **설정>테마**에서 '시스템'을 선택할 수 없던 문제를 수정했습니다.
- `frontend/src/components/settings/Select.jsx` & `frontend/src/components/settings/SettingSwitch.jsx`: 온라인에서만 사용되는 prop을 optional화 했습니다. 추후 타입화하겠습니다.

'설정>테마'에서 '시스템'이 없어졌던 문제 해결

---

frontend/src/pages/settings/Profile.jsx

**설정>프로필**에서 유저네임에 g, q, p 같은 글자가 포함될 시 아래가 잘려보이던 문제를 해결했습니다.
| Before | After |
|---|---|
| <img width="349" alt="Screenshot 2025-03-27 at 15 07 07" src="https://github.com/user-attachments/assets/5b8fab20-e14e-4594-891b-522482a78703" /> | <img width="349" alt="Screenshot 2025-03-27 at 15 07 00" src="https://github.com/user-attachments/assets/66a9f0b4-bff9-4093-86c3-83dd2cf7c6d7" /> |

설정>프로필에서 유저네임 아래가 짤리는 문제 해결

---

backend/notifications/urls.py

`notifications.urls.py`에서 `path("<str:id>/", ...)`이 `path("reminders/", ...)`보다 위에 있어 405에러가 뜨던 오류를 수정하였습니다.

작업 생성 시 뜨던 405 에러 수정

---

frontend/src/components/home/Header.tsx

- `frontend/src/components/home/Header.tsx`를 타입화했습니다.
- 동 파일의 로딩 조건을 `isFetching`에서 `isLoading`으로 변경해 캐시가 있을 경우 스켈레톤이 표시되지 않도록 수정했습니다.

홈의 프로필 사진 로딩 조건을 isLoading으로 변경

---

frontend/public/global.css

토스트가 띄워졌을 때 네비바가 눌리지 않는 문제가 있어 수정했습니다.
아마 #331 PR에서 react-toastify v11로 업데이트했을 때부터 생긴 증상 같습니다.

모바일 화면에서 토스트가 띄워졌을 때 네비바가 눌리지 않는 문제 해결

---

frontend/src/components/common/FilterButtonGroup.tsx
frontend/src/components/intro/DemoTheme.tsx

- NotificationsPage와 DemoTheme(IntroPage 속)에서 쓰이는 `FilterButtonGroup`을 타입화했습니다.
- `FilterButtonGroup`의 transition이 처음에는 실행되지 않도록 수정했습니다.
| Before | After |
|---|---|
| https://github.com/user-attachments/assets/bcf46f44-f142-41b6-ba5d-d3451c0a1c23 | https://github.com/user-attachments/assets/5f13df73-eb47-43a0-8fbd-d0eefa2b7cde |

FilterButtonGroup 타입화 & 처음에는 transition이 실행되지 않도록 수정

---

frontend/src/pages/NotificationsPage.jsx

#435 PR 이후 NotificationsPage에서 로딩이 되지 않던 문제를 해결했습니다.
- 원인: 올바르지 않은 `queryKey` 지정으로 인해 호출 함수로 데이터가 넘어가지 않음
- 해결: `queryKey` 수정

NotificationsPage에서 로딩이 되지 않던 문제 해결

---

.github/workflows/reviewer.yaml

random-reviewer-discord 액션을 0.2.2로 업데이트합니다.
변경사항은 다음과 같습니다:
- 풀 리퀘스트 저자가 스스로 리뷰 코멘트를 작성했을 때(코멘트 답장도 포함) 디스코드 알림이 발생하던 문제 해결

Bump random-reviewer-discord from 0.2.1 to 0.2.2

---

deploy/README.md
frontend/Dockerfile
frontend/README.md
frontend/package.json
frontend/pnpm-lock.yaml

dependabot이 [pnpm v10을 지원](https://github.com/dependabot/dependabot-core/issues/11246#issuecomment-2935428790)하기 시작했습니다. 우리 프로젝트의 pnpm도 v9에서 v10으로 판올림합니다.

Bump pnpm to v10

---

frontend/src/components/home/InstallPeak.tsx

'Peak을 앱처럼 사용하기' 모듈이 전부 노출에서 'PWA를 설치할 수 있는 Safari 환경이고 PWA가 아닐 때'로 변경했습니다.
| Firefox | iOS (미설치) | iOS (PWA 속) |
|--|--|--|
| <img width="782" height="660" alt="Screenshot 2025-08-24 at 17 42 22" src="https://github.com/user-attachments/assets/ade29dd6-28b6-44ae-8dcf-007c50e82115" /> | <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-24 at 17 42 28" src="https://github.com/user-attachments/assets/7bc4ebd2-26e0-4322-935b-0725da31e8e7" /> | <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-24 at 17 42 43" src="https://github.com/user-attachments/assets/be4d48e7-b4e4-4c2b-b6c1-8a586b0cf76e" /> |
안드로이드 환경은 당장 테스트할 기기가 없고 안드로이드용 설치 가이드도 제작이 되지 않은 관계로 추후 지원할 계획입니다.

홈의 PWA 유도 모듈의 출현 조건 지정

---

frontend/src/assets/locales/en/translation.json
frontend/src/assets/locales/ko/translation.json
frontend/src/components/tasks/utils/useTaskDateStatus.tsx

- `translation.json`의 `task.days_left` 영문 번역에서 숫자와 단어가 띄어쓰기가 되지 않던 문제가 있었습니다.
```
3days left
```
- 문자열 concat 대신에 번역 내부 변수를 사용하게 하여 언어별로 다르게 처리할 수 있게 수정했습니다.
- `days_left` 번역은 `diff=1`일 때는 쓰이지 않기 때문에 별도의 수사 처리는 하지 않았습니다.

days_left 영문 번역에서 띄어쓰기가 되지 않던 문제 해결

---

frontend/public/global.css

- `html`의 `width`가 `100vw`로 설정되어 있어 가로 스크롤이 생기는 문제가 있어 `100%`로 변경하고 `height`도 `min-height`로 설정해 불필요한 스크롤바가 생길 상황을 최소화했습니다.
- 원래 `overflow-x: hidden`으로 설정되어 있어 문제 파악을 못했는데, `useStopScroll` 오류로 발견했습니다.
- `100vw`인 상태에서 `body`에 `overflow: auto`를 추가하고, 가로 스크롤바가 생기는 것을 확인한다.
- `100%`로 속성을 변경하고 브라우저 새로고침 후 `overflow` 속성을 추가해도 가로 스크롤바가 생기지 않는 것을 확인한다.

html의 width를 100%로 수정
